# Update your database.yml based in database-docker.yml


# Install the MySQL driver
#   gem install mysql2

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: db
  username: root
  password: password


development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  host: 
  database: 
  username: 
  password: 
