FROM node:8.11.3-slim as node

# ******Multi stage ********
FROM ruby:<%= ruby_version %> as builder

ENV RAILS_ENV=production
ENV NODE_ENV=production

# install common dev libs
RUN apt-get update -qq && apt-get dist-upgrade -y && apt-get install -y \
    build-essential \
    apt-transport-https \
    git \
    curl
<% if database == "mysql" %>
# install mysql
RUN apt-get update -qq && apt-get dist-upgrade -y && apt-get install -y libmysqlclient-dev mysql-client
<% elsif database == "postgresql" %>
# install postgresql
RUN apt-get update -qq && apt-get dist-upgrade -y && apt-get install -y libpq-dev postgresql-client
<% end %>

# install Nodejs 8.11.3 and Yarn 1.6.0
ENV NODE_VERSION 8.11.3
ENV YARN_VERSION 1.6.0
COPY --from=node /usr/local/bin/ /usr/local/bin/
COPY --from=node /usr/local/lib/ /usr/local/lib/
COPY --from=node /opt/yarn-v1.6.0/ /opt/yarn-v1.6.0/

RUN mkdir /app
WORKDIR /app

# ************Install Ruby gems***************************
# Invalidate gems cache if change Gemfile or Gemfile.lock
COPY Gemfile Gemfile.lock /app/
RUN bundle install -j 4 --without development test staging --deployment
# ******************************************************

# ********Install Node packages************************
# Invalidate node_modules cache if yarn.lock change
COPY package.json yarn.lock /app/
RUN yarn install --pure-lockfile --production
# ****************************************************

COPY . /app
RUN rails assets:precompile

# *******************************************
# **************** Multi Stage **************
# *******************************************
FROM ruby:<%= ruby_version %>

ENV RAILS_ENV=production
ENV NODE_ENV=production

<% if database == "mysql" %>
# install mysql
RUN apt-get update -qq && apt-get dist-upgrade -y && apt-get install -y mysql-client º
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
<% elsif database == "postgresql" %>
# install postgresql
RUN apt-get update -qq && apt-get dist-upgrade -y && apt-get install -y postgresql-client \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
<% end %>
# install node 8.9.1 LTS
ENV NODE_VERSION 8.11.3
COPY --from=node /usr/local/bin/ /usr/local/bin/
COPY --from=node /usr/local/lib/ /usr/local/lib/

WORKDIR /app

# ************Copy only Rails app, prevent copy unnecessary files (.dockerignore don't work)***************************
COPY --from=builder /app/app /app/app
COPY --from=builder /app/config /app/config
COPY --from=builder /app/bin /app/bin
COPY --from=builder /app/db /app/db
COPY --from=builder /app/lib /app/lib
COPY --from=builder /app/public /app/public
COPY --from=builder /app/vendor /app/vendor
COPY --from=builder /app/Gemfile /app/Gemfile.lock app/Rakefile /app/config.ru /app/
# *********************************************************************************************************************

COPY --from=builder /usr/local/bundle /usr/local/bundle
COPY --from=builder /app/docker/production/rails/entrypoint.sh /app/docker/production/rails/entrypoint.sh

CMD ["/app/docker/production/rails/entrypoint.sh"]
