FROM ruby:<%= ruby_version %>

# install common dev libs
RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  git

# install editors
RUN apt-get install -y \
  nano \
  vim

# http libs for download
RUN apt-get install -y \
  curl \
  ca-certificates \
  openssl \
  apt-transport-https \
  gnupg2

<% if database == "mysql" %>
# install mysql
RUN apt-get install -y mysql-client libmysqlclient-dev
<% elsif database == "postgresql" %>
# install postgresql
RUN apt-get install -y postgresql-client
<% end %>

# install node 8.9.1 LTS
RUN curl -sL https://deb.nodesource.com/setup_8.x | bin/bash -
RUN apt-get update && apt-get install -y nodejs

# install yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install yarn

RUN mkdir /app
WORKDIR /app
COPY . /app

<% if @id_rsa == 'yes' %>
RUN mkdir /root/.ssh
RUN cp id_rsa /root/.ssh/id_rsa
# RUN chmod 0644 /root/.ssh/id_rsa
RUN touch /root/.ssh/known_hosts
RUN eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa && ssh-add -l && ssh-add -L && echo "Host github.com\n\tIdentityFile ~/.ssh/id_rsa" >> /root/.ssh/config
RUN ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
<% end %>
