workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - docker:
          requires:
            - test

version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # run tests!
      - run:
          name: run tests
          command: |
            rspec
  docker:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          docker build --no-cache -t devmasx/dockerize-stack -t devmasx/dockerize-stack:$CIRCLE_TAG .
      # deploy the image
      # - run: docker push company/app:$CIRCLE_BRANCH
