version: '3'
services:
  web:
    build:
      dockerfile: ./docker/development/Dockerfile
      context: ./

    container_name: web
    stdin_open: true
    tty: true
    command: "bash ./docker/development/entrypoint.sh"
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    # env_file:
    #   - web.env

  db:
    image: 'mysql:5.7'
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - database:/var/lib/mysql

  # redis:
  #   image: redis
  #     ports:
  #       - "6379:6379"
  # mailcatcher:
  #   image: schickling/mailcatcher
  #   ports:
  #     - 1025:1025
  #     - 1080:1080

volumes:
  gems:
  database:

# USAGE

# Execute a container for run rails console or rake tasks
# docker-compose run --rm web bash

# Attach the container when use binding.pry
# docker attach web

# When run rails generator you need to run
# sudo chown -R $USER:$USER .
