# BUILD STAGE
FROM node:<%= @nodejs_version %>-slim as build

#RUN apk -u add git openssh

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

# FINAL STAGE
FROM nginx:1.15
WORKDIR /app

COPY --from=build /app/public /app/public
COPY ./nginx/conf.d/default.conf /app/default.conf

CMD /bin/bash -c "envsubst < /app/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

# docker build -t gatsby-app .
# docker run --rm -e PORT=8080 -p 8080:8080 gatsby-app
