FROM node:10.13.0-slim as node

# ******Multi stage ********
FROM ruby:<%= ruby_version %>

# Install common dev libs
RUN apt-get update -qq && apt-get install -y \
  build-essential \
  vim \
  git

<% if database == "mysql" %>
# Install Mysql
RUN apt-get install -y mysql-client libmysqlclient-dev
<% elsif database == "postgresql" %>
# Install Postgresql
RUN apt-get install -y postgresql-client libpq-dev
<% end %>

# Install Nodejs 10.13.0 and Yarn 1.10.1
ENV NODE_VERSION 10.13.0
ENV YARN_VERSION 1.10.1
COPY --from=node /usr/local/bin/ /usr/local/bin/
COPY --from=node /usr/local/lib/ /usr/local/lib/
COPY --from=node /opt/yarn-v1.10.1/ /opt/yarn-v1.10.1/

WORKDIR /app

<% if @github_private == 'yes' %>
# Private repository
ARG GITHUB_TOKEN
ARG GITHUB_USERNAME
RUN bundle config github.com ${GITHUB_USERNAME}:${GITHUB_TOKEN}
<% end %>

# Invalidate gems cache if change Gemfile or Gemfile.lock
COPY Gemfile Gemfile.lock /app/
RUN bundle install -j 4

# Invalidate node_modules cache if package.json or yarn.lock
COPY package.json yarn.lock /app/
RUN yarn install --pure-lockfile

COPY . /app

