FROM ruby:<%= ruby_version %>

# Install common dev libs
RUN apt-get update -qq && apt-get install -y \
  build-essential vim git

<% if database == "mysql" %>
# Install Mysql
RUN apt-get install -y mysql-client libmysqlclient-dev
<% elsif database == "postgresql" %>
# Install Postgresql
RUN apt-get install -y postgresql-client libpq-dev
<% end %>

# Install Nodejs 10.x
RUN curl -sL https://deb.nodesource.com/setup_10.x | bin/bash -\
  && apt-get install -y nodejs

WORKDIR /app

<% if @github_private == 'yes' %>
# Private repository
ARG GITHUB_TOKEN
ARG GITHUB_USERNAME
RUN bundle config github.com ${GITHUB_USERNAME}:${GITHUB_TOKEN}
<% end %>

# Invalidate gems cache if change Gemfile or Gemfile.lock
COPY Gemfile Gemfile.lock /app/
RUN bundle install -j 4

# Invalidate node_modules cache if package.json or package-lock.json
COPY package.json package-lock.json /app/
RUN npm ci

COPY . .
